import type Database from "better-sqlite3";
import { effectiveEvidenceSql } from "@/lib/research/evidenceTrust";

export type ResearchTaskType =
  | "missing_evidence"
  | "stale_evidence"
  | "low_confidence"
  | "missing_profile"
  | "missing_field"
  | "sync_failure"
  | "report_quality";

export type ResearchTaskStatus = "open" | "in_progress" | "completed" | "dismissed";
export type ResearchTaskTargetType = "company" | "field" | "relation" | "evidence" | "report" | "industry";

export type ResearchTask = {
  id: number;
  taskKey: string;
  taskType: ResearchTaskType;
  status: ResearchTaskStatus;
  priority: number;
  title: string;
  description: string;
  targetType: ResearchTaskTargetType;
  stockCode: string;
  shortName: string;
  categoryId: number | null;
  categoryName: string;
  relationId: number | null;
  relationType: string;
  confidence: string;
  evidenceId: number | null;
  evidenceCount: number;
  reportId: number | null;
  fieldKey: string;
  provider: string;
  sourceRef: string;
  resolution: string;
  autoGenerated: boolean;
  canComplete: boolean;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
};

type AutomaticTaskInput = {
  taskKey: string;
  taskType: ResearchTaskType;
  priority: number;
  title: string;
  description: string;
  targetType: ResearchTaskTargetType;
  stockCode?: string | null;
  categoryId?: number | null;
  relationId?: number | null;
  evidenceId?: number | null;
  reportId?: number | null;
  fieldKey?: string;
  sourceRef?: string;
};

type TaskRow = Omit<ResearchTask, "autoGenerated" | "canComplete"> & {
  autoGenerated: number;
  relationVerified: string | null;
  fieldStatus: string | null;
  profileExists: number;
  reportStatus: string | null;
  reportQualityJson: string | null;
};

export function syncAutomaticResearchTasks(db: Database.Database) {
  const detected = detectAutomaticTasks(db);
  const taskKeys = new Set(detected.map((task) => task.taskKey));

  db.transaction(() => {
    const upsert = db.prepare(`
      insert into research_tasks (
        task_key, task_type, status, priority, title, description, target_type,
        stock_code, category_id, relation_id, evidence_id, report_id, field_key,
        source_ref, auto_generated
      )
      values (
        @taskKey, @taskType, 'open', @priority, @title, @description, @targetType,
        @stockCode, @categoryId, @relationId, @evidenceId, @reportId, @fieldKey,
        @sourceRef, 1
      )
      on conflict(task_key) do update set
        task_type = excluded.task_type,
        status = case
          when research_tasks.status = 'completed' then 'open'
          else research_tasks.status
        end,
        priority = excluded.priority,
        title = excluded.title,
        description = excluded.description,
        target_type = excluded.target_type,
        stock_code = excluded.stock_code,
        category_id = excluded.category_id,
        relation_id = excluded.relation_id,
        evidence_id = excluded.evidence_id,
        report_id = excluded.report_id,
        field_key = excluded.field_key,
        source_ref = excluded.source_ref,
        resolution = case
          when research_tasks.status = 'completed' then ''
          else research_tasks.resolution
        end,
        completed_at = case
          when research_tasks.status = 'completed' then ''
          else research_tasks.completed_at
        end,
        updated_at = current_timestamp
      where research_tasks.status = 'completed'
         or research_tasks.task_type != excluded.task_type
         or research_tasks.priority != excluded.priority
         or research_tasks.title != excluded.title
         or research_tasks.description != excluded.description
         or research_tasks.target_type != excluded.target_type
         or coalesce(research_tasks.stock_code, '') != coalesce(excluded.stock_code, '')
         or coalesce(research_tasks.category_id, 0) != coalesce(excluded.category_id, 0)
         or coalesce(research_tasks.relation_id, 0) != coalesce(excluded.relation_id, 0)
         or coalesce(research_tasks.evidence_id, 0) != coalesce(excluded.evidence_id, 0)
         or coalesce(research_tasks.report_id, 0) != coalesce(excluded.report_id, 0)
         or research_tasks.field_key != excluded.field_key
         or research_tasks.source_ref != excluded.source_ref
    `);
    for (const task of detected) {
      upsert.run({
        ...task,
        stockCode: task.stockCode ?? null,
        categoryId: task.categoryId ?? null,
        relationId: task.relationId ?? null,
        evidenceId: task.evidenceId ?? null,
        reportId: task.reportId ?? null,
        fieldKey: task.fieldKey ?? "",
        sourceRef: task.sourceRef ?? "",
      });
    }

    const openAutomatic = db.prepare(
      "select id, task_key as taskKey from research_tasks where auto_generated = 1 and status in ('open', 'in_progress')",
    ).all() as Array<{ id: number; taskKey: string }>;
    const complete = db.prepare(`
      update research_tasks
      set status = 'completed',
          resolution = '系统检测到问题已经解除',
          completed_at = current_timestamp,
          updated_at = current_timestamp
      where id = ?
    `);
    for (const task of openAutomatic) {
      if (!taskKeys.has(task.taskKey)) complete.run(task.id);
    }
  })();

  return detected.length;
}

export function listResearchTasks(db: Database.Database, options: { includeCompleted?: boolean } = {}) {
  const where = options.includeCompleted ? "" : "where task.status in ('open', 'in_progress')";
  const rows = db.prepare(`
    select
      task.id,
      task.task_key as taskKey,
      task.task_type as taskType,
      task.status,
      task.priority,
      task.title,
      task.description,
      task.target_type as targetType,
      coalesce(task.stock_code, '') as stockCode,
      coalesce(company.short_name, '') as shortName,
      task.category_id as categoryId,
      coalesce(category.name, '') as categoryName,
      task.relation_id as relationId,
      coalesce(relation.relation_type, '') as relationType,
      coalesce(relation.confidence, '') as confidence,
      relation.verification_status as relationVerified,
      task.evidence_id as evidenceId,
      coalesce((
        select count(*) from evidences evidence
        where evidence.relation_id = task.relation_id
          and (${effectiveEvidenceSql("evidence")})
      ), 0) as evidenceCount,
      task.report_id as reportId,
      task.field_key as fieldKey,
      coalesce(field.provider, '') as provider,
      field.status as fieldStatus,
      task.source_ref as sourceRef,
      task.resolution,
      task.auto_generated as autoGenerated,
      case when profile.stock_code is null then 0 else 1 end as profileExists,
      report.status as reportStatus,
      report.quality_json as reportQualityJson,
      task.created_at as createdAt,
      task.updated_at as updatedAt,
      task.completed_at as completedAt
    from research_tasks task
    left join companies company on company.stock_code = task.stock_code
    left join categories category on category.id = task.category_id
    left join company_category_relations relation on relation.id = task.relation_id
    left join company_field_facts field
      on field.stock_code = task.stock_code
     and field.field_key = task.field_key
     and field.provider = task.source_ref
    left join company_research_profiles profile on profile.stock_code = task.stock_code
    left join research_documents report on report.id = task.report_id
    ${where}
    order by
      case task.status when 'open' then 0 when 'in_progress' then 1 else 2 end,
      task.priority desc,
      task.updated_at desc,
      task.id desc
  `).all() as TaskRow[];

  return rows.map(mapTaskRow);
}

export function getResearchTask(db: Database.Database, taskId: number) {
  return listResearchTasks(db, { includeCompleted: true }).find((task) => task.id === taskId) ?? null;
}

export function startResearchTask(db: Database.Database, taskId: number) {
  const result = db.prepare(`
    update research_tasks
    set status = 'in_progress', updated_at = current_timestamp
    where id = ? and status = 'open'
  `).run(taskId);
  return result.changes > 0 ? getResearchTask(db, taskId) : null;
}

export function completeResearchTask(db: Database.Database, taskId: number, resolution: string) {
  syncAutomaticResearchTasks(db);
  const task = getResearchTask(db, taskId);
  if (!task) throw new Error("任务不存在");
  if (task.status === "completed") return task;

  if (task.taskType === "low_confidence" && task.relationId) {
    db.prepare(`
      update company_category_relations
      set verification_status = 'verified',
          verified_at = current_timestamp,
          updated_at = current_timestamp
      where id = ?
    `).run(task.relationId);
  } else if (!task.canComplete) {
    throw new Error("问题仍未解除，请先打开定位目标完成补证、同步或修订");
  }

  db.prepare(`
    update research_tasks
    set status = 'completed',
        resolution = ?,
        completed_at = current_timestamp,
        updated_at = current_timestamp
    where id = ?
  `).run(resolution.trim() || "已人工核验并完成", taskId);
  return getResearchTask(db, taskId);
}

export function dismissResearchTask(db: Database.Database, taskId: number, resolution: string) {
  const result = db.prepare(`
    update research_tasks
    set status = 'dismissed',
        resolution = ?,
        completed_at = current_timestamp,
        updated_at = current_timestamp
    where id = ? and status in ('open', 'in_progress')
  `).run(resolution.trim() || "已确认暂不处理", taskId);
  return result.changes > 0 ? getResearchTask(db, taskId) : null;
}

function detectAutomaticTasks(db: Database.Database) {
  return [
    ...detectRelationTasks(db),
    ...detectProfileTasks(db),
    ...detectFieldTasks(db),
    ...detectSyncFailureTasks(db),
    ...detectReportTasks(db),
    ...detectAiTasks(db),
  ];
}

function detectRelationTasks(db: Database.Database): AutomaticTaskInput[] {
  const rows = db.prepare(`
    select
      relation.id as relationId,
      relation.stock_code as stockCode,
      relation.category_id as categoryId,
      relation.relation_type as relationType,
      relation.confidence,
      relation.verification_status as verificationStatus,
      company.short_name as shortName,
      category.name as categoryName,
      sum(case when evidence.id is not null and (${effectiveEvidenceSql("evidence")}) then 1 else 0 end) as activeEvidenceCount,
      sum(case when evidence.id is not null and evidence.is_expired = 1 then 1 else 0 end) as staleEvidenceCount
    from company_category_relations relation
    join companies company on company.stock_code = relation.stock_code
    join categories category on category.id = relation.category_id and category.is_active = 1
    left join evidences evidence on evidence.relation_id = relation.id
    where ${activeRelationSql("relation")}
    group by relation.id
  `).all() as Array<{
    relationId: number;
    stockCode: string;
    categoryId: number;
    relationType: string;
    confidence: string;
    verificationStatus: string;
    shortName: string;
    categoryName: string;
    activeEvidenceCount: number;
    staleEvidenceCount: number;
  }>;

  return rows.flatMap((row) => {
    const tasks: AutomaticTaskInput[] = [];
    if (Number(row.activeEvidenceCount) === 0) {
      tasks.push({
        taskKey: `relation:${row.relationId}:missing-evidence`,
        taskType: "missing_evidence",
        priority: 80,
        title: `${row.shortName}缺少有效关系证据`,
        description: `“${row.categoryName}”关系没有可用且未过期的来源，请补充公告、年报或权威研报。`,
        targetType: "relation",
        stockCode: row.stockCode,
        categoryId: row.categoryId,
        relationId: row.relationId,
      });
    }
    if (Number(row.staleEvidenceCount) > 0) {
      tasks.push({
        taskKey: `relation:${row.relationId}:stale-evidence`,
        taskType: "stale_evidence",
        priority: 65,
        title: `${row.shortName}关系证据已过期`,
        description: `“${row.categoryName}”存在 ${row.staleEvidenceCount} 条过期资料，需要重新核验时效性。`,
        targetType: "relation",
        stockCode: row.stockCode,
        categoryId: row.categoryId,
        relationId: row.relationId,
      });
    }
    if ((row.relationType === "待验证" || row.confidence === "低") && row.verificationStatus !== "verified") {
      tasks.push({
        taskKey: `relation:${row.relationId}:low-confidence`,
        taskType: "low_confidence",
        priority: 85,
        title: `${row.shortName}产业链关系待核验`,
        description: `当前为“${row.relationType} · ${row.confidence}置信度”，需要人工确认关系边界与依据。`,
        targetType: "relation",
        stockCode: row.stockCode,
        categoryId: row.categoryId,
        relationId: row.relationId,
      });
    }
    return tasks;
  });
}

function detectProfileTasks(db: Database.Database): AutomaticTaskInput[] {
  const rows = db.prepare(`
    select company.stock_code as stockCode, company.short_name as shortName,
           min(relation.category_id) as categoryId, min(relation.id) as relationId
    from companies company
    join company_category_relations relation on relation.stock_code = company.stock_code
    left join company_research_profiles profile on profile.stock_code = company.stock_code
    where profile.stock_code is null
      and ${activeRelationSql("relation")}
    group by company.stock_code
  `).all() as Array<{ stockCode: string; shortName: string; categoryId: number | null; relationId: number }>;
  return rows.map((row) => ({
    taskKey: `company:${row.stockCode}:missing-profile`,
    taskType: "missing_profile",
    priority: 45,
    title: `${row.shortName}研究档案待建立`,
    description: "主营构成、产业链位置、核心优势、催化剂和风险尚未形成结构化档案。",
    targetType: "company",
    stockCode: row.stockCode,
    categoryId: row.categoryId,
    relationId: row.relationId,
  }));
}

function activeRelationSql(alias: string) {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(alias)) throw new Error("关系 SQL 别名无效");
  return `(
    ${alias}.is_watchlist = 1
    or exists (select 1 from evidences active_evidence where active_evidence.relation_id = ${alias}.id)
    or exists (select 1 from company_field_facts active_fact where active_fact.stock_code = ${alias}.stock_code)
    or exists (select 1 from sync_tasks active_sync where active_sync.stock_code = ${alias}.stock_code)
    or exists (select 1 from ai_research_runs active_ai where active_ai.stock_code = ${alias}.stock_code)
    or exists (select 1 from ai_research_reports active_ai_report where active_ai_report.stock_code = ${alias}.stock_code)
    or exists (select 1 from research_documents active_report where active_report.stock_code = ${alias}.stock_code)
    or exists (
      select 1 from research_notes active_note
      where (active_note.target_type = 'company' and active_note.target_id = ${alias}.stock_code)
         or (active_note.target_type = 'relation' and active_note.target_id = cast(${alias}.id as text))
    )
  )`;
}

function detectFieldTasks(db: Database.Database): AutomaticTaskInput[] {
  const rows = db.prepare(`
    select fact.stock_code as stockCode, company.short_name as shortName,
           fact.field_key as fieldKey, fact.provider, fact.provider_label as providerLabel,
           fact.status, fact.error,
           (select min(category_id) from company_category_relations where stock_code = fact.stock_code) as categoryId
    from company_field_facts fact
    join companies company on company.stock_code = fact.stock_code
    where fact.status in ('missing', 'failed')
  `).all() as Array<{
    stockCode: string;
    shortName: string;
    fieldKey: string;
    provider: string;
    providerLabel: string;
    status: "missing" | "failed";
    error: string;
    categoryId: number | null;
  }>;
  return rows.map((row) => ({
    taskKey: `field:${row.stockCode}:${row.fieldKey}:${row.provider}:${row.status}`,
    taskType: row.status === "failed" ? "sync_failure" : "missing_field",
    priority: row.status === "failed" ? 90 : 60,
    title: `${row.shortName}${fieldLabel(row.fieldKey)}${row.status === "failed" ? "同步失败" : "待补"}`,
    description: row.status === "failed"
      ? `${row.providerLabel || row.provider}未能返回该字段。${row.error || "请重新同步或更换来源。"}`
      : `${row.providerLabel || row.provider}未提供${fieldLabel(row.fieldKey)}，请补充替代来源。`,
    targetType: "field",
    stockCode: row.stockCode,
    categoryId: row.categoryId,
    fieldKey: row.fieldKey,
    sourceRef: row.provider,
  }));
}

function detectSyncFailureTasks(db: Database.Database): AutomaticTaskInput[] {
  const rows = db.prepare(`
    select task.id, task.stock_code as stockCode, task.task_type as taskType,
           task.source, task.error, task.message, company.short_name as shortName,
           (select min(category_id) from company_category_relations where stock_code = task.stock_code) as categoryId
    from sync_tasks task
    join companies company on company.stock_code = task.stock_code
    join (
      select stock_code, task_type, max(id) as id
      from sync_tasks group by stock_code, task_type
    ) latest on latest.id = task.id
    where task.status in ('failed', 'partial')
  `).all() as Array<{
    id: number;
    stockCode: string;
    taskType: string;
    source: string;
    error: string;
    message: string;
    shortName: string;
    categoryId: number | null;
  }>;
  return rows.map((row) => ({
    taskKey: `sync:${row.stockCode}:${row.taskType}:${row.id}`,
    taskType: "sync_failure",
    priority: 95,
    title: `${row.shortName}资料同步未完成`,
    description: row.error || row.message || "后台资料同步失败，请重试。",
    targetType: "company",
    stockCode: row.stockCode,
    categoryId: row.categoryId,
    sourceRef: `sync-task:${row.id}`,
  }));
}

function detectReportTasks(db: Database.Database): AutomaticTaskInput[] {
  const rows = db.prepare(`
    select report.id, report.title, report.stock_code as stockCode,
           case
             when report.stock_code is null then report.category_id
             when exists (
               select 1 from company_category_relations relation
               where relation.stock_code = report.stock_code and relation.category_id = report.category_id
             ) then report.category_id
             else (select min(category_id) from company_category_relations where stock_code = report.stock_code)
           end as categoryId,
           report.subject_label as subjectLabel,
           report.status, report.quality_json as qualityJson
    from research_documents report
    where report.status != 'ready'
  `).all() as Array<{
    id: number;
    title: string;
    stockCode: string | null;
    categoryId: number | null;
    subjectLabel: string;
    status: string;
    qualityJson: string;
  }>;
  return rows.map((row) => {
    const quality = parseQuality(row.qualityJson);
    return {
      taskKey: `report:${row.id}:quality`,
      taskType: "report_quality",
      priority: quality.score < 60 ? 75 : 55,
      title: `${row.title}待完善`,
      description: quality.issues[0] || `当前质量得分 ${quality.score}，需要补齐证据、章节或风险披露。`,
      targetType: "report",
      stockCode: row.stockCode,
      categoryId: row.categoryId,
      reportId: row.id,
      sourceRef: row.subjectLabel,
    };
  });
}

function detectAiTasks(db: Database.Database): AutomaticTaskInput[] {
  const companyRows = db.prepare(`
    select run.id, run.stock_code as stockCode,
           case
             when exists (
               select 1 from company_category_relations relation
               where relation.stock_code = run.stock_code and relation.category_id = run.category_id
             ) then run.category_id
             else (select min(category_id) from company_category_relations where stock_code = run.stock_code)
           end as categoryId,
           run.result_json as resultJson, company.short_name as shortName
    from ai_research_runs run
    join companies company on company.stock_code = run.stock_code
    where run.status = 'completed'
  `).all() as Array<{ id: number; stockCode: string; categoryId: number | null; resultJson: string; shortName: string }>;
  const universalRows = db.prepare(`
    select run.id, run.subject_label as subjectLabel, run.category_id as categoryId,
           run.result_json as resultJson
    from universal_research_runs run
    where run.status = 'completed'
  `).all() as Array<{ id: number; subjectLabel: string; categoryId: number | null; resultJson: string }>;

  const companyTasks = companyRows.flatMap((row) => {
    const result = parseAiResult(row.resultJson);
    if (result.confidence !== "低" && result.citationCount > 0) return [];
    return [{
      taskKey: `ai-run:${row.id}:low-confidence`,
      taskType: "low_confidence" as const,
      priority: 70,
      title: `${row.shortName} AI 结论待核验`,
      description: result.citationCount === 0 ? "AI 结论未绑定可追溯证据。" : "AI 主审给出低置信度，需要补充证据或反证。",
      targetType: "company" as const,
      stockCode: row.stockCode,
      categoryId: row.categoryId,
      sourceRef: `ai-run:${row.id}`,
    }];
  });
  const universalTasks = universalRows.flatMap((row) => {
    const result = parseAiResult(row.resultJson);
    if (result.confidence !== "低" && result.citationCount > 0) return [];
    return [{
      taskKey: `universal-run:${row.id}:low-confidence`,
      taskType: "low_confidence" as const,
      priority: 65,
      title: `${row.subjectLabel}研究结论待核验`,
      description: result.citationCount === 0 ? "研究结论未绑定可追溯证据。" : "主审置信度偏低，需要补充来源。",
      targetType: "industry" as const,
      categoryId: row.categoryId,
      sourceRef: `universal-run:${row.id}`,
    }];
  });
  return [...companyTasks, ...universalTasks];
}

function mapTaskRow(row: TaskRow): ResearchTask {
  return {
    ...row,
    evidenceCount: Number(row.evidenceCount),
    autoGenerated: row.autoGenerated === 1,
    canComplete: canCompleteTask(row),
  };
}

function canCompleteTask(row: TaskRow) {
  if (row.taskType === "low_confidence" && row.relationId) return true;
  if (row.taskType === "missing_profile") return row.profileExists === 1;
  if (row.taskType === "missing_field" || row.taskType === "sync_failure") return row.fieldStatus === "available";
  if (row.taskType === "report_quality") return row.reportStatus === "ready" && parseQuality(row.reportQualityJson ?? "{}").score >= 75;
  return false;
}

function parseQuality(value: string) {
  try {
    const parsed = JSON.parse(value) as { score?: unknown; issues?: unknown };
    return {
      score: typeof parsed.score === "number" ? parsed.score : 0,
      issues: Array.isArray(parsed.issues) ? parsed.issues.filter((item): item is string => typeof item === "string") : [],
    };
  } catch {
    return { score: 0, issues: [] as string[] };
  }
}

function parseAiResult(value: string) {
  try {
    const parsed = JSON.parse(value) as { confidence?: unknown; citations?: unknown };
    return {
      confidence: typeof parsed.confidence === "string" ? parsed.confidence : "",
      citationCount: Array.isArray(parsed.citations) ? parsed.citations.length : 0,
    };
  } catch {
    return { confidence: "", citationCount: 0 };
  }
}

function fieldLabel(fieldKey: string) {
  const labels: Record<string, string> = {
    businessComposition: "主营构成",
    revenue: "营业收入",
    netProfit: "归母净利润",
    operatingCashFlow: "经营现金流",
    debtRatio: "资产负债率",
    price: "最新股价",
    peTtm: "市盈率",
    announcements: "公司公告",
    researchReports: "机构研报",
  };
  return labels[fieldKey] ?? fieldKey;
}
